src/main/java/itakademija/java2015/jpa/assigment1/entities/Address.java
package itakademija.java2015.jpa.assigment1.entities;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

//@Entity
@Embeddable
public class Address implements Serializable {
	private static final long serialVersionUID = -1276076195792170244L;
//	@Id
//	@GeneratedValue
//	private Long id;
	
	
	/**
	 * 
	 */
	private String country;
	private String city;
	private String street;
//	@Column(name="BUILDING")
	private String building;
	private String flat;

	
//	public Long getId() {
//		return id;
//	}
//
//
//	public void setId(Long id) {
//		this.id = id;
//	}


	public String getCountry() {
		return country;
	}


	public void setCountry(String country) {
		this.country = country;
	}


	public String getCity() {
		return city;
	}


	public void setCity(String city) {
		this.city = city;
	}


	public String getStreet() {
		return street;
	}


	public void setStreet(String street) {
		this.street = street;
	}


	public String getBuilding() {
		return building;
	}


	public void setBuilding(String building) {
		this.building = building;
	}


	public String getFlat() {
		return flat;
	}


	public void setFlat(String flat) {
		this.flat = flat;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((building == null) ? 0 : building.hashCode());
		result = prime * result + ((city == null) ? 0 : city.hashCode());
		result = prime * result + ((country == null) ? 0 : country.hashCode());
		result = prime * result + ((flat == null) ? 0 : flat.hashCode());
		result = prime * result + ((street == null) ? 0 : street.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Address)) {
			return false;
		}
		Address other = (Address) obj;
		if (building == null) {
			if (other.building != null) {
				return false;
			}
		} else if (!building.equals(other.building)) {
			return false;
		}
		if (city == null) {
			if (other.city != null) {
				return false;
			}
		} else if (!city.equals(other.city)) {
			return false;
		}
		if (country == null) {
			if (other.country != null) {
				return false;
			}
		} else if (!country.equals(other.country)) {
			return false;
		}
		if (flat == null) {
			if (other.flat != null) {
				return false;
			}
		} else if (!flat.equals(other.flat)) {
			return false;
		}
		if (street == null) {
			if (other.street != null) {
				return false;
			}
		} else if (!street.equals(other.street)) {
			return false;
		}
		return true;
	}


	@Override
	public String toString() {
		return "Address [country=" + country + ", city=" + city + ", street=" + street + ", building="
				+ building + ", flat=" + flat + "]";
	}
}

src/main/java/itakademija/java2015/jpa/assigment1/entities/AuthorTag.java
package itakademija.java2015.jpa.assigment1.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity implementation class for Entity: AuthorTag
 *
 */
@Entity
public class AuthorTag implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	private Long id;
	
	@Column(nullable=false, unique=true)
	private String tag;
	@Temporal(TemporalType.TIMESTAMP)
	private Date createdOn;

	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public AuthorTag() {
		super();
	}   
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}   
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((createdOn == null) ? 0 : createdOn.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((tag == null) ? 0 : tag.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AuthorTag)) {
			return false;
		}
		AuthorTag other = (AuthorTag) obj;
		if (createdOn == null) {
			if (other.createdOn != null) {
				return false;
			}
		} else if (!createdOn.equals(other.createdOn)) {
			return false;
		}
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		if (tag == null) {
			if (other.tag != null) {
				return false;
			}
		} else if (!tag.equals(other.tag)) {
			return false;
		}
		return true;
	}
	@Override
	public String toString() {
		return "AuthorTag [id=" + id + ", tag=" + tag + ", createdOn=" + createdOn + "]";
	}
	
   
}

src/main/java/itakademija/java2015/ui/controllers/AddNewBookPageBean.java
package itakademija.java2015.ui.controllers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import itakademija.java2015.jpa.assigment1.entities.Author;
import itakademija.java2015.jpa.assigment1.entities.Book;
import itakademija.java2015.jpa.assigment1.entities.Genre;
import itakademija.java2015.jpa.assigment1.entities.repositories.AuthorRepository;
import itakademija.java2015.jpa.assigment1.entities.repositories.BookRepository;
import itakademija.java2015.jpa.assigment1.entities.repositories.GenreRepository;

public class AddNewBookPageBean {
	static final Logger log = LoggerFactory.getLogger(AddNewBookPageBean.class);
	/**
	 * Repositories
	 */
	private AuthorRepository authorRepo;
	private BookRepository bookRepo;

	/**
	 * Other pages for functionality re-use
	 */
	private AuthorsListPageBean authorsListPageBean;
	
	/**
	 * Holds data for entering new book information like title and release date.
	 * In other words - it backs up form for new book.
	 */
	private Book newBook;
	private String genre;
	
	/**
	 * Initialization method for bean
	 */
	public void init() {
		newBook = new Book();
	}
	
	public String addNew() {
		/**
		 * At this point, book data is stored in newBook variable, we can save it to DB
		 */
		Author author = authorsListPageBean.getData().getCurrentAuthor();
		log.debug("Before saving book, got author: {}", author);
		log.debug("New book data: {}", newBook);
		newBook.setAuthor(author);
		author.addBook(newBook);
		this.setGenreForBook(this.genre);
		authorRepo.save(author);
		
		
		return AuthorsListPageBean.NAV_LIST_AUTHORS;
	}
	
	
	public String getGenre() {
		return genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	public AuthorsListPageBean getAuthorsListPageBean() {
		return authorsListPageBean;
	}
	public void setAuthorsListPageBean(AuthorsListPageBean authorsListPageBean) {
		this.authorsListPageBean = authorsListPageBean;
	}
	public AuthorRepository getAuthorRepo() {
		return authorRepo;
	}
	public void setAuthorRepo(AuthorRepository authorRepo) {
		this.authorRepo = authorRepo;
	}
	public BookRepository getBookRepo() {
		return bookRepo;
	}
	public void setBookRepo(BookRepository bookRepo) {
		this.bookRepo = bookRepo;
	}
	
	public void setGenreForBook (String genre){
		newBook.getGenres().add(new Genre(genre));
	}
	
	public Book getNewBook() {
		return newBook;
	}
	public void setNewBook(Book newBook) {
		this.newBook = newBook;
	}
}

src/main/java/itakademija/java2015/ui/controllers/AuthorsListPageBean.java
package itakademija.java2015.ui.controllers;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import itakademija.java2015.jpa.assigment1.entities.Author;
import itakademija.java2015.jpa.assigment1.entities.AuthorTag;
import itakademija.java2015.jpa.assigment1.entities.repositories.AuthorRepository;

/**
 * This class controls behavior of Author list page. Reacts to user commands and
 * handles navigation
 *
 */
public class AuthorsListPageBean {
	private static final String NAV_SHOW_AUTHORS_BY_TAG = "show-tags";

	static final Logger log = LoggerFactory.getLogger(AuthorsListPageBean.class);

	/**
	 * Navigation outcomes
	 */
	public static final String NAV_SHOW_ADD_BOOK = "show-add-book";
	public static final String NAV_LIST_AUTHORS = "list-authors";

	/**
	 * This class holds user-input data. Basically it is just container. This
	 * class is responsible JUST FOR HOLDING ANY DATA in session
	 *
	 */
	public static class AuthorsListPageData implements Serializable {

		private static final long serialVersionUID = -7847613490719023414L;

		/**
		 * Holds data of new Author form fields
		 */
		@Valid
		
		private Author newAuthor;

		/**
		 * Holds data for currently selected author
		 */
		@Valid
		private Author currentAuthor;

		private String tags;
		
		private String searchTag;
		
		private List<Author> foundAuthors;

		/**
		 * Initialization method for bean (called after bean is created)
		 */
		public void init() {
			newAuthor = new Author();
			foundAuthors = new ArrayList<>();
		}

		public String getSearchTag() {
			return searchTag;
		}

		public void setSearchTag(String searchTag) {
			this.searchTag = searchTag;
		}

		public List<Author> getFoundAuthors() {
			return foundAuthors;
		}

		public void setFoundAuthors(List<Author> foundAuthors) {
			this.foundAuthors = foundAuthors;
		}

		public String getTags() {
			return tags;
		}

		public void setTags(String tags) {
			this.tags = tags;
		}

		public Author getCurrentAuthor() {
			return currentAuthor;
		}

		public void setCurrentAuthor(Author currentAuthor) {
			this.currentAuthor = currentAuthor;
		}

		public Author getNewAuthor() {
			return newAuthor;
		}

		public void setNewAuthor(Author newAuthor) {
			this.newAuthor = newAuthor;
		}
	} // end of AuthorsListPageData

	/**
	 * Data container/holder
	 */
	private AuthorsListPageData data;

	/**
	 * repositories
	 */
	private AuthorRepository authorRepo;

	/**
	 * Add new author to DB as it was entered in form
	 * 
	 * @return JSF outcome
	 */
	public String addNew() {
		String tagsString = data.getTags();
		if (tagsString != null) {
			List<AuthorTag> tagList = convertTagStringToTagList(tagsString);

			data.newAuthor.setTags(tagList);
		}
		authorRepo.save(data.newAuthor);
		data.newAuthor = new Author(); // clear the form values
		data.tags = "";
		return NAV_LIST_AUTHORS;
	}
	public String convertTagListToTagString(List<AuthorTag> tags) {
		String ret = "";
		for (AuthorTag tag: tags) {
			ret += tag.getTag() + " ";
		}
		return ret;
	}
	private List<AuthorTag> convertTagStringToTagList(String tagsString) {
		log.debug("Converting string[{}]", tagsString);
		List<AuthorTag> tagList = new ArrayList<>();

		if (tagsString != null) {
			/**
			 * This splits string at any sequence of blanks (spaces, tabs, ...) and returns chopped list of strings
			 */
			String[] res = tagsString.split("\\s+");
			log.debug("Split size: {}", res.length);
			List<String> tagsArray = Arrays.asList(res);
			log.debug("List size:{}", tagsArray.size());
			for (String tagStr : tagsArray) {
				AuthorTag t = null;
				t = authorRepo.findTag(tagStr);
				if (t == null)
				{
					log.debug("New tag: {}", tagStr);
					t = new AuthorTag();
					t.setCreatedOn(new Date());
				}
				else
					log.debug("Existing tag: {}", tagStr);
				log.debug("Adding single tag: [{}]", tagStr);
				t.setTag(tagStr);
				tagList.add(t);
			}
		}
		return tagList;
	}

	/**
	 * Delete selected author
	 * 
	 * @param author
	 * @return JSF outcome
	 */
	public String deleteSelected(Author author) {
		if (author == null)
			FacesContext.getCurrentInstance().addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_WARN, "Warning!", "Author being deleted is null?"));
		else {
			if (author.getName().equalsIgnoreCase("Jonas"))
				FacesContext.getCurrentInstance().addMessage(null,
						new FacesMessage(FacesMessage.SEVERITY_INFO, "Info", "You are deleting Jonas!"));
			authorRepo.delete(author);
		}
		return NAV_LIST_AUTHORS;
	}

	/**
	 * This method just remembers selected author and redirects user to new page
	 */
	public String showAddBookPage(Author a) {
		log.debug("Will store selected author for later access in Add new Book form: {}", a);
		data.currentAuthor = a;
		return NAV_SHOW_ADD_BOOK;
	}

	public String searchTags() {
		//save to session
		data.foundAuthors = authorRepo.findAllAuthorsByTag(data.getSearchTag());
		return NAV_SHOW_AUTHORS_BY_TAG;
	}
	public AuthorsListPageData getData() {
		return data;
	}

	public void setData(AuthorsListPageData data) {
		this.data = data;
	}

	public AuthorRepository getAuthorRepo() {
		return authorRepo;
	}

	public void setAuthorRepo(AuthorRepository authorRepo) {
		this.authorRepo = authorRepo;

	}

	public List<Author> getAuthorList() {
		return authorRepo.findAll();
	}
}

src/main/java/itakademija/java2015/ui/controllers/BookListBean.java
package itakademija.java2015.ui.controllers;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import itakademija.java2015.jpa.assigment1.entities.Book;
import itakademija.java2015.jpa.assigment1.entities.Genre;
import itakademija.java2015.jpa.assigment1.entities.repositories.BookRepository;

public class BookListBean {

	static final Logger log = LoggerFactory.getLogger(BookListBean.class);
	
	public static final String NAV_SHOW_ADD_BOOK = "show-add-book";
	public static final String NAV_LIST_BOOKS = "list-books";
	
	public static class BookListPageData implements Serializable {

		private static final long serialVersionUID = -7847613490719023414L;
		
		@Valid
		private Book newBook;
		
		@Valid
		private Book currentBook;
		
		private List<Book> foundBooks;
		
		private String titles;
		
		private String searchTitle;
		
		private String authorNames;
		
		private String searchAuthorName;
		
		private String genres;
		
		private String searchGenres;
		
		private Integer releaseYears;
		
		private Integer searchYear;
		
		public void init() {
			newBook = new Book();
			foundBooks = new ArrayList<Book>();
		}

		public Book getNewBook() {
			return newBook;
		}

		public void setNewBook(Book newBook) {
			this.newBook = newBook;
		}

		public Book getCurrentBook() {
			return currentBook;
		}

		public void setCurrentBook(Book currentBook) {
			this.currentBook = currentBook;
		}

		public List<Book> getFoundBooks() {
			return foundBooks;
		}

		public void setFoundBooks(List<Book> foundBooks) {
			this.foundBooks = foundBooks;
		}

		public String getTitles() {
			return titles;
		}

		public void setTitles(String titles) {
			this.titles = titles;
		}

		public String getSearchTitle() {
			return searchTitle;
		}

		public void setSearchTitle(String searchTitle) {
			this.searchTitle = searchTitle;
		}

		public String getAuthorNames() {
			return authorNames;
		}

		public void setAuthorNames(String authorNames) {
			this.authorNames = authorNames;
		}

		public String getSearchAuthorName() {
			return searchAuthorName;
		}

		public void setSearchAuthorName(String searchAuthorName) {
			this.searchAuthorName = searchAuthorName;
		}

		public String getGenres() {
			return genres;
		}

		public void setGenres(String genres) {
			this.genres = genres;
		}

		public String getSearchGenres() {
			return searchGenres;
		}

		public void setSearchGenres(String searchGenres) {
			this.searchGenres = searchGenres;
		}

		public Integer getReleaseYears() {
			return releaseYears;
		}

		public void setReleaseYears(Integer releaseYears) {
			this.releaseYears = releaseYears;
		}

		public Integer getSearchYear() {
			return searchYear;
		}

		public void setSearchYear(Integer searchYear) {
			this.searchYear = searchYear;
		}
		
	}
	private BookListPageData data;

	private BookRepository bookRepo;

	public BookListPageData getData() {
		return data;
	}

	public void setData(BookListPageData data) {
		this.data = data;
	}

	public BookRepository getBookRepo() {
		return bookRepo;
	}

	public void setBookRepo(BookRepository bookRepo) {
		this.bookRepo = bookRepo;
	}

	public List<Book> getBookList() {
		return bookRepo.findAllBooks();
	}
	
	public String convertGenreListToGenreString(List<Genre> genres) {
		String result = "";
		for (Genre genre: genres) {
			result += genre.getGenre() + " ";
		}
		return result;
	}
	
	public String deleteSelectedBook(Book book) {
		if (book == null)
			FacesContext.getCurrentInstance().addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_WARN, "Warning!", "Book you want to delete is null"));
		else {
			FacesContext.getCurrentInstance().addMessage(null,
						new FacesMessage(FacesMessage.SEVERITY_INFO, "Info", "You are deleting" + book.getTitle()));
			bookRepo.delete(book);
		}
		return NAV_LIST_BOOKS;
	}
	
	public String showAddBookPage(Book b) {
		log.debug("Will store selected book for later access in Add new Book form: {}", b);
		data.currentBook = b;
		return NAV_SHOW_ADD_BOOK;
	}
	
	public String searchBooks() {
		//save to session
		data.foundBooks = bookRepo.findBook(data.getSearchAuthorName(), data.getSearchYear(), data.getSearchTitle(), data.getSearchGenres());
		return NAV_LIST_BOOKS;
	}
}

src/main/webapp/addBook.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="sablonas.xhtml">

	<ui:define name="turinys">
		<h:form>
			<p:messages id="messages" showDetail="true" autoUpdate="true"
				closable="true" />
			<p:panel id="basic" header="Book details" style="margin-bottom:20px">
				<h:panelGrid id="grid" columns="3" cellpadding="5">
				
					<h:outputLabel for="bookTitle" value="Book title"></h:outputLabel>
					<h:inputText id="bookTitle" value="#{addBookPage.newBook.title}">
						<f:validateBean />
					</h:inputText>
					<p:message for="bookTitle" />
					
					<h:outputLabel for="bookGenre" value="Book genre"></h:outputLabel>
					<h:inputText id="bookGenre" value="#{addBookPage.genre}">
						<f:validateBean />
					</h:inputText>
					<p:message for="bookGenre" />
					
					<h:outputLabel for="bookReleaseDate"
						value="Book release date (YYYY-MM-DD)"></h:outputLabel>
					<h:inputText id="bookReleaseDate"
						value="#{addBookPage.newBook.releaseDate}"
						converterMessage="Use format YYYY-MM-DD">
						<f:convertDateTime pattern="yyyy-M-d" />
					</h:inputText>
					
					<p:message for="bookReleaseDate" />
				</h:panelGrid>

				<h:commandButton action="#{addBookPage.addNew}" value="Add new"></h:commandButton>
			</p:panel>
		</h:form>

	</ui:define>

	<ui:define name="pavadinimas">
 	 	Add new book
 	 </ui:define>

</ui:composition>

src/main/webapp/authors.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="sablonas.xhtml">

	<ui:define name="turinys">
		<h:form>
			
			<p:messages id="messages" showDetail="false" autoUpdate="true"
				closable="true" />

			<p:dataTable value="#{authorListPage.authorList}" var="author">
				<p:column headerText="Id">
					<h:outputText value="#{author.id}" />
				</p:column>

				<p:column headerText="Name">
					<h:outputText value="#{author.name}" />
				</p:column>

				<p:column headerText="Lastname">
					<h:outputText value="#{author.lastname}" />
				</p:column>

				<p:column headerText="Books">
					<h:dataTable value="#{author.books}" var="book" border="0">
						<h:column>
		  						#{book.title} (#{bookList.convertGenreListToGenreString(book.genres)}) (#{book.releaseDate})
	  					</h:column>
					</h:dataTable>
				</p:column>
				<p:column headerText="Tags">
					<h:outputText
						value="#{authorListPage.convertTagListToTagString(author.tags)}" />
				</p:column>

				<p:column headerText="">
					<h:commandButton value="Delete"
						action="#{authorListPage.deleteSelected(author)}" />
					<h:commandButton value="Add Book"
						action="#{authorListPage.showAddBookPage(author)}" />
				</p:column>
			</p:dataTable>


		</h:form>
		<h:form>
			<p:panel id="basic" header="Author" style="margin-bottom:20px">
				<h:panelGrid id="grid" columns="3" cellpadding="5">
					<h:outputLabel for="author_name" value="Author name"></h:outputLabel>
					<h:inputText id="author_name"
						value="#{authorListPageData.newAuthor.name}">
						<f:validateBean />
					</h:inputText>
					<p:message for="author_name" />

					<h:outputLabel for="author_lastname" value="Author lastname"></h:outputLabel>
					<h:inputText id="author_lastname"
						value="#{authorListPageData.newAuthor.lastname}"></h:inputText>
					<p:message for="author_lastname" display="icon" />
					<h:outputLabel for="tags" value="Author tags"></h:outputLabel>
					<h:inputText id="tags" value="#{authorListPageData.tags}"></h:inputText>
					<p:message for="tags" display="icon" />
				</h:panelGrid>

			</p:panel>

			<h:commandButton action="#{authorListPage.addNew}" value="Add new"
				update="grid"></h:commandButton>
		</h:form>

	</ui:define>

	<ui:define name="pavadinimas">
 	 	Add new book
 	 </ui:define>

</ui:composition>

src/main/webapp/footer.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
      
<ui:composition> 
   <h:graphicImage library="image" name="footer.png" />
</ui:composition>
</html>

src/main/webapp/main.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ps="http://java.sun.com/jsf/passthrough">
	
	<h:head>
	<title>Find your book</title>
	<h:outputStylesheet name="styles.css"></h:outputStylesheet>
	</h:head>
	
<h:body>

	<h:form>
	<p:messages id="messages" showDetail="false" autoUpdate="true"
				closable="true" />
				
	<p:panel id="basic" header="Books Search" style="margin-bottom:20px">
				<h:panelGrid id="grid" columns="3" cellpadding="5">
				
					<h:outputLabel for="book_title" value="Book title"></h:outputLabel>
					<h:inputText id="book_title" value="#{bookListPageData.searchTitle}">
						<f:validateBean />
					</h:inputText>
					<p:message for="book_title" />

					<h:outputLabel for="author" value="Author name or last name"></h:outputLabel>
					<h:inputText id="author" value="#{bookListPageData.searchAuthorName}"></h:inputText>
					<p:message for="author" display="icon" />
					
					<h:outputLabel for="genres" value="Book genre"></h:outputLabel>
					<h:inputText id="genres" value="#{bookListPageData.searchGenres}"></h:inputText>
					<p:message for="genres" display="icon" />
					
					<h:outputLabel for="year" value="Release Year"></h:outputLabel>
					<h:inputText id="year" value="#{bookListPageData.searchYear}"></h:inputText>
					<p:message for="year" display="icon" />
				</h:panelGrid>
			</p:panel>
				
		<p>
			<h:commandButton value="Find Book"
				action="#{bookList.searchBooks}" update="grid">
			</h:commandButton>
		</p>
		<p>
		<p:dataTable value="#{bookListPageData.foundBooks}" var="book">
					<p:column headerText="Book Title">
	 				#{book.title}
	 				</p:column>
	 				
					<p:column headerText="Author">
	 				#{book.author.name} #{book.author.lastname}
	 				</p:column>
	 				
	 				<p:column headerText="Release Year">
	 				#{book.releaseDate}
	 				</p:column>
	 				
	 				<p:column headerText="Genre">
	 				#{bookList.convertGenreListToGenreString(book.genres)}
	 				</p:column>
					<p:column headerText="Actions">

						<!-- <p:commandLink actionListener="#{workersView.update(worker.code)}"
							update="@form" value="Edit" resetValues="true"
							immediate="true" /> -->

						<p:commandLink actionListener="#{bookList.deleteSelectedBook(book)}"
							update="@form" value="Delete" immediate="true">

							<p:confirm header="Confirmation" message="Delete this data?"
								icon="ui-icon-alert" />
						</p:commandLink>
					</p:column>
				</p:dataTable>
				</p>

				<p:confirmDialog global="true">
					<p:commandButton value="Yes" type="button"
						styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
					<p:commandButton value="No" type="button"
						styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
				</p:confirmDialog>
			</h:form>
	</h:body>
</html>
			
		
		